version: '3'

services:
  app:
    build:
      context: .
    volumes:
      - ./:/app
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp"
    tty: true

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:alpine
    environment:
      POSTGRES_DB: toread
      # You should definitely change the password in production
      POSTGRES_PASSWORD: toread
      POSTGRES_USER: toread
    ports:
      - '5432'
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
